### ISSUE TITLE
[BUG] Inventory cache only returns first 14 items

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#115]
**Describe the bug**
With the inventory closed the inventory debug shows this overlay:
![image](https://user-images.githubusercontent.com/34009165/194500372-23d00eb7-fbf6-4cb6-9a78-d77d4d1ed915.png)
I always assumed it only showed the first 14 items as to not over crowd the screen with debug information.

Turns out Inventory.isFul() is false, and also Inventory. Stream().count() in fact only returns 14, when my inventory is full.

**To Reproduce/Line of code causing issue**
1. fill inventory
2. change tabs or close inventory
3. check Inventory.isFull()/Inventory.stream().count()

**Expected behavior**
Return all 28 item slots

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://gyazo.com/6f96646ed4e8fdf0e04813ee80bdf0c5)

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by iDznPB** [comment]
Also one showing the same bug without stacked coins in the inventory (as per discord)
![image](https://user-images.githubusercontent.com/34009165/194511906-ae2648ad-72e4-4601-990b-8a546b6dbae1.png)

**Comment by constt** [comment]
should be resolved on next

**Comment by iDznPB** [comment]
Working nicely,
The paint overlay still doesn't show all 28 items though when i turn on the debug, but I can iterate and find all of them, is this intentional?

**Comment by constt** [comment]
@iDznPB paint overlay should show all, what do you see?

**Comment by iDznPB** [comment]
@constt the first 16
![image](https://user-images.githubusercontent.com/34009165/195024495-70553981-a3f1-41fc-a7b7-7972c0b02077.png)

**Comment by constt** [comment]
@iDznPB should be fixed in next

**Comment by iDznPB** [comment]
Beautiful
