### ISSUE TITLE
[BUG] Bank keyboard input NPE

### ISSUE THREAD

**Issue by iDznPB** [powbot/issues#45]
**Describe the bug**
Withdraw X - typing in value cause NPE and script crash

**To Reproduce/Line of code causing issue**
```
Bank.withdraw("Whatever you have in the bank", 3);
```

**Expected behavior**
Type the value passed and return

**Logs**
```
[SEVERE] java.lang.NullPointerException: events must not be null
	at org.powbot.mobile.input.Keyboard.type(Keyboard.kt:76)
	at org.powbot.api.Input.send(Input.kt:127)
	at org.powbot.api.Input.sendln(Input.kt:140)
	at org.powbot.api.rt4.Bank.withdraw(Bank.kt:477)
	at org.powbot.api.rt4.Bank.withdrawAmount(Bank.kt:573)
	at org.powbot.api.rt4.Bank.withdraw(Bank.kt:445)
	at org.powbot.api.rt4.Bank.withdraw(Bank.kt:388)
	at Tests.Test.poll(Test.java:64)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invokeSuspend(ScriptManager.kt:372)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:8)
	at org.powbot.mobile.script.ScriptManager$runScript$4.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:370)
	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:25)
	at org.powbot.mobile.script.ScriptManager$start$2.invokeSuspend(ScriptManager.kt:162)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Emulator or device (please complete the following information):**
 - Device/Emulator: BS
 - OS: P64
 - Arch: ARM

**Comment by constt** [comment]
@iDznPB resolved in next build

**Comment by iDznPB** [comment]
@constt 
no longer NPE's but doesn't send the key to the game, just sits on this screen
![image](https://user-images.githubusercontent.com/34009165/187652429-5eb039ce-7a02-4f3f-9167-4725ddacd016.png)

**Comment by iDznPB** [comment]
Input.send() & Input.sendLn() no longer send keys at all either

```08-31 12:34:33.611  9210  9267 I System.out: send
08-31 12:34:33.612  9210  9246 E PowBotNative: ProcessInputEvent(50839552, 0x7fe4996ecdc0, 0x7fe47e072cc0 0x7fe4a30e5860)
08-31 12:34:33.614  9210  9246 I chatty  : uid=10072(com.jagex.oldscape.android) Thread-5490 identical 12 lines
08-31 12:34:33.614  9210  9246 E PowBotNative: ProcessInputEvent(50839552, 0x7fe4996ecdc0, 0x7fe47e072cc0 0x7fe4a30e5860)
08-31 12:34:33.643  9210  9252 D EGL_emulation: eglMakeCurrent: 0x7fe48296f000: ver 3 1 (tinfo 0x7fe4829cd120)
08-31 12:34:33.646  9210  9252 D EGL_emulation: eglMakeCurrent: 0x7fe48296fc00: ver 3 1 (tinfo ```

**Comment by constt** [comment]
@iDznPB Could you test sending text in game chat please, I tested that and it appeared to work

**Comment by iDznPB** [comment]
I tried earlier both in this window and in game chat neither worked.
I've tried now and it seems to be working now..

**Comment by iDznPB** [comment]
@constt input.send() works, but bank.withdraw() still doesn't send the text to the "Enter amount:" box

**Comment by iDznPB** [comment]
@constt found the issue; it will only send the keys if user input is allowed on the client, i.e. the icon is green on the bar

**Comment by constt** [comment]
@iDznPB This should now be fixed

**Comment by 5Henveru2** [comment]
@constt this is still broken, I'm using Input.sendln and it will only type when the toggleable "Script Input" setting is on, which often gets disabled on script start.

**Comment by rvbiljouw** [comment]
> @constt this is still broken, I'm using Input.sendln and it will only type when the toggleable "Script Input" setting is on, which often gets disabled on script start.

this should be fixed in the latest build

**Comment by iDznPB** [comment]
@rvbiljouw cleared cache, re-installed, but still doesn't send any keys with input blocked.
Testing on Bank.withdraw(item, 9);
It successfully clicks withdraw X
```
[INFO] Received expected action - GameActionEvent(v0=8, widgetId=786445, rawOp=1007, id=6, interaction='Withdraw-X', rawEntityName='<col=ff9040>Vial of water</col>', mouseX=-1, mouseY=-1)
```
just doesn't type the amount.

**Comment by 5Henveru2** [comment]
@constt it sends the keys with input blocked now, but it doesn't press enter.  Tested both Input.sendln and Bank.withdraw(name, amount)

**Comment by constt** [comment]
@iDznPB fixed in next

**Comment by iDznPB** [comment]
Tested and working <3
